"""add_ethnicity_and_gsa_number_to_gymnasts

Revision ID: 604bed2f1eb3
Revises: d580371f305c
Create Date: 2026-07-20 05:34:15.375926

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "604bed2f1eb3"
down_revision: str | Sequence[str] | None = "d580371f305c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Autogenerate emitted a bare op.add_column() referencing this Enum inline, but
    # SQLAlchemy only auto-creates a Postgres enum TYPE via a Table-create event -- an
    # ALTER TABLE ADD COLUMN on an existing table never fires it, so the column DDL
    # below would fail with "type ethnicity does not exist" unless the type is created
    # explicitly first.
    ethnicity_enum = sa.Enum(
        "white", "black", "coloured", "indian", "prefer_not_to_say", name="ethnicity"
    )
    ethnicity_enum.create(op.get_bind(), checkfirst=True)
    op.add_column("gymnasts", sa.Column("ethnicity", ethnicity_enum, nullable=True))
    op.add_column("gymnasts", sa.Column("gsa_number", sa.String(length=32), nullable=True))
    op.create_unique_constraint("uq_gymnast_gsa_number", "gymnasts", ["gsa_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_gymnast_gsa_number", "gymnasts", type_="unique")
    op.drop_column("gymnasts", "gsa_number")
    op.drop_column("gymnasts", "ethnicity")
    # ### end Alembic commands ###
    sa.Enum(name="ethnicity").drop(op.get_bind(), checkfirst=False)
